function voltageMeasured = fibRobot_importVoltageSignal(filename, dataLines)
%IMPORTFILE Import data from a text file
%  TENSILECOMP20210129105703FORCE = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the numeric
%  data.
%
%  TENSILECOMP20210129105703FORCE = IMPORTFILE(FILE, DATALINES) reads
%  data for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  tensilecomp20210129105703force = importfile("C:\Users\augus\Google Drive\FIBRobot\testingTheForce\tempForce_29012021\tensile_comp_2021-01-29-10-57-03_force.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-Jan-2021 10:12:48

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["times", "forceN"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
voltageMeasured = readtable(filename, opts);

%% Convert to output type
voltageMeasured = table2array(voltageMeasured);
end